name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact to deploy
        required: false
        type: string
        default: dist
    outputs:
      result:
        description: The result of the workflow
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Infomation
        run: echo "Deploy & Uploading..."
      - name: Set Result Output
        run: echo "step-result" >> $GITHUB_OUTPUT
